# Generated by Django 4.2.7 on 2023-12-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graduation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True, unique=True)),
                ('sem1', models.FloatField(blank=True, null=True)),
                ('sem2', models.FloatField(blank=True, null=True)),
                ('sem3', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'graduation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schooling',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True, unique=True)),
                ('tenth', models.FloatField(blank=True, null=True)),
                ('tewelth', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'schooling',
                'managed': False,
            },
        ),
    ]
